# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: NextJs deployment

on:
  push:
    branches:
      - main
    paths:
      - poker-tracker-client-next/**
      - .github/workflows/main_poker-radar-next.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install sharp
        run: |
          npm install --os=linux --cpu=x64 sharp

      - name: npm install, build, and test
        run: |
          cd poker-tracker-client-next
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone
        env:
          NEXTAUTH_URL: "https://poker-radar.com"
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_API_URL: "https://poker-radar.com/api"
          NEXT_PUBLIC_DEFAULT_DOMAIN: "https://poker-radar.com"
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
          FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
          FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
          FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
          FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
          FIREBASE_MEASUREMENT_ID: "G-Z85VHGN1ME"
          NEXT_PUBLIC_SIGNAL_R_URL: "https://poker-radar-signal-r-api-b7bba8fxgybketfk.germanywestcentral-01.azurewebsites.net/hub"
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          APPLICATION_INSIGHTS_CONNECTION_STRING: ${{secrets.APPLICATION_INSIGHTS_CONNECTION_STRING}}
          SA_CONN_STRING: ${{secrets.SA_CONN_STRING}}
          CASINO_IMAGES_CONTAINER: "casinos-images"
          CASINO_TOURNAMENTS_CONTAINER: "casinos-tournaments"

      - name: Zip artifact for deployment
        run: zip release.zip poker-tracker-client-next/build/standalone -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'poker-radar-next'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B8B92CB14611455185D1661468B95020 }}
          package: .
